# For dev usage
version: "3"

services:
  mongodb:
    container_name: junc-api-db-dev
    image: mongo:latest
    volumes:
      - junc-dev-volume:/data/db:rw
    ports:
      - 27017:27017

volumes:
  junc-dev-volume:
